#ifndef _RCGLOBALS_H
#define _RCGLOBALS_H

#define DEBUG_PRT I2CSerial
#define PAGE_HEIGHT GxGDEW027C44_PAGE_HEIGHT
#define PAGE_WIDTH GxGDEW027C44_WIDTH
#define PAGE_COUNT GxGDEW027C44_PAGES

#define DISPLAY_PORTRAIT true

#endif