#ifndef _RCGLOBALS_H
#define _RCGLOBALS_H
	#define LECT_VER "0.7"

    #define MAX_DEEPSLEEP_SECONDS 4294

	#define DEBUG_PRT I2CSerial
	#define PAGE_HEIGHT GxGDEW027C44_PAGE_HEIGHT
	#define PAGE_WIDTH GxGDEW027C44_WIDTH
	#define PAGE_COUNT GxGDEW027C44_PAGES

	#define DISPLAY_PORTRAIT true

	#define _PSIZE_X GxGDEW027C44_WIDTH
	#define _PSIZE_Y GxGDEW027C44_HEIGHT

	#if DISPLAY_PORTRAIT == true
		#define PANEL_SIZE_Y _PSIZE_X
		#define PANEL_SIZE_X _PSIZE_Y
	#else
		#define PANEL_SIZE_X _PSIZE_X
		#define PANEL_SIZE_Y _PSIZE_Y
	#endif

#endif